# ============================================================
#  fastapi_app/endpoints/endpoints_cortex.py
#  MiniStudioGPT — CORTEX v1.5
#  API Endpoints pour le moteur Cortex (analyse, suggestion, réparation)
# ============================================================

from fastapi import APIRouter, HTTPException, Query
from fastapi_app.services.cortex_service import CortexService
from datetime import datetime
from pathlib import Path
import json

router = APIRouter(prefix="/cortex", tags=["Cortex"])
service = CortexService(".")

def _log_action(action: str):
    log_file = Path("memory/session_audit.log")
    log_file.parent.mkdir(parents=True, exist_ok=True)
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(f"[CORTEX-ENDPOINT] {datetime.now().isoformat()} — {action}\n")

# ============================================================
# /cortex/analyze
# ============================================================
@router.post("/analyze")
async def analyze():
    _log_action("Analyse demandée via endpoint /cortex/analyze")
    try:
        result = await service.run_analysis()
        return {
            "status": "success",
            "endpoint": "/cortex/analyze",
            "timestamp": datetime.utcnow().isoformat(),
            "details": result,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ============================================================
# /cortex/suggest
# ============================================================
@router.post("/suggest")
async def suggest(topic: str = Query("general", description="Thème de suggestion")):
    _log_action(f"Suggestion demandée (topic={topic}) via /cortex/suggest")
    try:
        result = await service.generate_suggestions(topic)
        return {
            "status": "success",
            "endpoint": "/cortex/suggest",
            "timestamp": datetime.utcnow().isoformat(),
            "details": result,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ============================================================
# /cortex/check-integrity
# ============================================================
@router.get("/check-integrity")
async def check_integrity():
    _log_action("Vérification d'intégrité via /cortex/check-integrity")
    try:
        project_map = Path("memory/project_map.json")
        if not project_map.exists():
            raise HTTPException(status_code=404, detail="project_map.json introuvable")
        data = json.loads(project_map.read_text(encoding="utf-8"))
        missing = [f for f in data.keys() if not Path(f).exists()]
        return {
            "status": "success",
            "endpoint": "/cortex/check-integrity",
            "missing_files": missing,
            "count_missing": len(missing),
            "timestamp": datetime.utcnow().isoformat(),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ============================================================
# /cortex/map-inspect
# ============================================================
@router.get("/map-inspect")
async def map_inspect():
    _log_action("Inspection de la project map via /cortex/map-inspect")
    try:
        project_map = Path("memory/project_map.json")
        if not project_map.exists():
            raise HTTPException(status_code=404, detail="project_map.json introuvable")
        data = json.loads(project_map.read_text(encoding="utf-8"))
        return {
            "status": "success",
            "endpoint": "/cortex/map-inspect",
            "modules_count": len(data),
            "details": list(data.keys())[:20],
            "timestamp": datetime.utcnow().isoformat(),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ============================================================
# /cortex/auto-fix
# ============================================================
@router.post("/auto-fix")
async def auto_fix():
    _log_action("Auto-fix global via /cortex/auto-fix")
    try:
        project_map = Path("memory/project_map.json")
        if not project_map.exists():
            raise HTTPException(status_code=404, detail="project_map.json introuvable")
        data = json.loads(project_map.read_text(encoding="utf-8"))
        missing_files = [f for f in data.keys() if not Path(f).exists()]
        repaired = []
        for f in missing_files:
            Path(f).parent.mkdir(parents=True, exist_ok=True)
            Path(f).write_text("# Auto-generated by Cortex Engine\n", encoding="utf-8")
            repaired.append(f)
        return {
            "status": "success",
            "endpoint": "/cortex/auto-fix",
            "files_repaired": repaired,
            "count": len(repaired),
            "timestamp": datetime.utcnow().isoformat(),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
